#include<stdio.h>
#include<string.h>
int main()
{
	int a,b,c,d,e,f,g,h,k[8][8];
	char l,m[100];
	for(a=0;a<8;a++)
	{
		for(b=0;b<8;b++)
		{
			k[a][b]=0;
		}
	}
	a=0;
	b=0;
	e=0;
	while(gets(m))
	{
		f=strlen(m);
		for(g=0,h=f+1;g<h;g++)
		{
			l=m[g];
		if(l=='/')
		{
			b++;
			a=0;
		}
		else if(g==f)
		{
			for(a=0;a<8;a++)
			{
				for(b=0;b<8;b++)
				{
					if(k[a][b]>1)
					{
						if(k[a][b]=='P')
						{
							if(a>0&&b>0)
							{
								if(!k[a-1][b-1])
								{
									k[a-1][b-1]=1;
									e--;
								}
							}
							if(a>0&&b<7)
							{
								if(!k[a-1][b+1])
								{
									k[a-1][b+1]=1;
									e--;
								}
							}
						}
						else if(k[a][b]=='p')
						{
							if(a<7&&b>0)
							{
								if(!k[a+1][b-1])
								{
									k[a+1][b-1]=1;
									e--;
								}
							}
							if(a<7&&b<7)
							{
								if(!k[a+1][b+1])
								{
									k[a+1][b+1]=1;
									e--;
								}
							}
						}
						else if(k[a][b]=='n')
						{
							if(a>1)
							{
								if(b>0)
								{
									if(!k[a-2][b-1])
									{
										k[a-2][b-1]=1;
										e--;
									}
								}
								if(b<7)
								{
									if(!k[a-2][b+1])
									{
										k[a-2][b+1]=1;
										e--;
									}
								}
							}
							if(a>0)
							{
								if(b>1)
								{
									if(!k[a-1][b-2])
									{
										k[a-1][b-2]=1;
										e--;
									}
								}
								if(b<6)
								{
									if(!k[a-1][b+2])
									{
										k[a-1][b+2]=1;
										e--;
									}
								}
							}
							if(a<6)
							{
								if(b>0)
								{
									if(!k[a+2][b-1])
									{
										k[a+2][b-1]=1;
										e--;
									}
								}
								if(b<7)
								{
									if(!k[a+2][b+1])
									{
										k[a+2][b+1]=1;
										e--;
									}
								}
							}
							if(a<7)
							{
								if(b>1)
								{
									if(!k[a+1][b-2])
									{
										k[a+1][b-2]=1;
										e--;
									}
								}
								if(b<6)
								{
									if(!k[a+1][b+2])
									{
										k[a+1][b+2]=1;
										e--;
									}
								}
							}
						}
						else if(k[a][b]=='b')
						{
							for(c=a-1,d=b-1;c>-1&&d>-1;c--,d--)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
							for(c=a+1,d=b-1;c<8&&d>-1;c++,d--)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
							for(c=a-1,d=b+1;c>-1&&d<8;c--,d++)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
							for(c=a+1,d=b+1;c<8&&d<8;c++,d++)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
						}
						else if(k[a][b]=='r')
						{
							for(c=a-1,d=b;c>-1;c--)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
							for(c=a+1,d=b;c<8;c++)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
							for(c=a,d=b-1;d>-1;d--)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
							for(c=a,d=b+1;d<8;d++)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
						}
						else if(k[a][b]=='q')
						{
							for(c=a-1,d=b-1;c>-1&&d>-1;c--,d--)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
							for(c=a+1,d=b-1;c<8&&d>-1;c++,d--)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
							for(c=a-1,d=b+1;c>-1&&d<8;c--,d++)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
							for(c=a+1,d=b+1;c<8&&d<8;c++,d++)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
							for(c=a-1,d=b;c>-1;c--)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
							for(c=a+1,d=b;c<8;c++)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
							for(c=a,d=b-1;d>-1;d--)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
							for(c=a,d=b+1;d<8;d++)
							{
								if(k[c][d]>1)
								{
									break;
								}
								else if(!k[c][d])
								{
									k[c][d]=1;
									e--;
								}
							}
						}
						else if(k[a][b]=='k')
						{
							if(a>0)
							{
								if(b>0)
								{
									if(!k[a-1][b-1])
									{
										k[a-1][b-1]=1;
										e--;
									}
								}
								if(!k[a-1][b])
								{
									k[a-1][b]=1;
									e--;
								}
								if(b<7)
								{
									if(!k[a-1][b+1])
									{
										k[a-1][b+1]=1;
										e--;
									}
								}
							}
							if(b>0)
							{
								if(!k[a][b-1])
								{
									k[a][b-1]=1;
									e--;
								}
							}
							if(b<7)
							{
								if(!k[a][b+1])
								{
									k[a][b+1]=1;
									e--;
								}
							}
							if(a<7)
							{
								if(b>0)
								{
									if(!k[a+1][b-1])
									{
										k[a+1][b-1]=1;
										e--;
									}
								}
								if(!k[a+1][b])
								{
									k[a+1][b]=1;
									e--;
								}
								if(b<7)
								{
									if(!k[a+1][b+1])
									{
										k[a+1][b+1]=1;
										e--;
									}
								}
							}
						}
					}
				}
			}
			printf("%d\n",e);
			for(a=0;a<8;a++)
			{
				for(b=0;b<8;b++)
				{
					k[a][b]=0;
				}
			}
			a=0;
			b=0;
			e=0;
		}
		else if(l<65)
		{
			l-=48;
			a+=l;
			e+=l;
		}
		else
		{
			if(l<97&&l!='P')
			{
				l+=32;
			}
			k[b][a++]=l;
		}
		}
	}
	return 0;
}