#include<stdio.h>
int main()
{
    int a,b,c,d,e,f,g,h,x,y,m,n,p,q,r,s,w,z;
    double i,j,k,l;
    scanf("%d",&x);
    for(x;x>0;x--)
    {
        scanf("%d%d%d%d%d%d%d%d",&a,&b,&c,&d,&e,&f,&g,&h);
		m=a;
		n=b;
		p=c;
		q=d;
		r=e;
		s=f;
		w=g;
		z=h;
		if(a>c)
		{
			y=a;
			a=c;
			c=y;
		}
		if(b>d)
		{
			y=b;
			b=d;
			d=y;
		}
		if(e>g)
		{
			y=e;
			e=g;
			g=y;
		}
		if(f>h)
		{
			y=f;
			f=h;
			h=y;
		}
		i=m-p;
        if(i==0)
        {
			if(a>=e&&a<=g&&b<=h&&d>=f)
			{
				printf("T\n");
			}
			else
			{
				printf("F\n");
			}
        }
        else
        {
			if(a>=e&&c<=g&&b>=f&&d<=h)
			{
				printf("T\n");
				continue;
			}
			j=n-q;
            j/=i;
            k=j*m;
            l=n;
			l-=k;
            i=j*r;
            i+=l;
            if(i>=f&&i<=h&&b<=i&&d>=i&&r>=a&&r<=c)
            {
				printf("%d %d %g\n",b,d,i);
                printf("T\n");
            }
            else
            {
                i=j*w;
                i+=l;
                if(i>=f&&i<=h&&b<=i&&d>=i&&w>=a&&w<=c)
                {
                    printf("T\n");
                }
                else
                {
                    i=s-l;
                    i/=j;
                    if(i>=e&&i<=g&&a<=i&&c>=i&&s>=b&&s<=d)
                    {
                        printf("T\n");
                    }
                    else
                    {
                        i=z-l;
                        i/=j;
                        if(i>=e&&i<=g&&a<=i&&c>=i&&z>=b&&z<=d)
                        {
                            printf("T\n");
                        }
						else
						{
							printf("F\n");
						}
                    }
                }
            }
        }
    }
    return 0;
}
