#include<stdio.h>
int main()
{
	int a,b,c,d,e,f,g,h,i,j;
	char k[25][26],x,y[626][2];
	h=0;
	while(scanf("%d%c",&a,&x)==2)
	{
		for(b=0;b<a;b++)
		{
			gets(k[b]);
		}
		for(b=0,f=0;b<a;b++)
		{
			for(c=0;c<a;c++)
			{
				if(k[b][c]==49)
				{
					f++;
					k[b][c]=48;
					y[0][0]=b;
					y[0][1]=c;
					d=1;
					for(e=0;e<d;e++)
					{
						i=y[e][0];
						j=y[e][1];
						if(i>0)
						{
							if(j>0)
							{
								if(k[i-1][j-1]==49)
								{
									k[i-1][j-1]=48;
									y[d][0]=i-1;
									y[d][1]=j-1;
									d++;
								}
							}
							if(k[i-1][j]==49)
							{
								k[i-1][j]=48;
								y[d][0]=i-1;
								y[d][1]=j;
								d++;
							}
							if(j<a-1)
							{
								if(k[i-1][j+1]==49)
								{
									k[i-1][j+1]=48;
									y[d][0]=i-1;
									y[d][1]=j+1;
									d++;
								}
							}
						}
						if(j>0)
						{
							if(k[i][j-1]==49)
							{
								k[i][j-1]=48;
								y[d][0]=i;
								y[d][1]=j-1;
								d++;
							}
						}
						if(j<a-1)
						{
							if(k[i][j+1]==49)
							{
								k[i][j+1]=48;
								y[d][0]=i;
								y[d][1]=j+1;
								d++;
							}
						}
						if(i<a-1)
						{
							if(j>0)
							{
								if(k[i+1][j-1]==49)
								{
									k[i+1][j-1]=48;
									y[d][0]=i+1;
									y[d][1]=j-1;
									d++;
								}
							}
							if(k[i+1][j]==49)
							{
								k[i+1][j]=48;
								y[d][0]=i+1;
								y[d][1]=j;
								d++;
							}
							if(j<a-1)
							{
								if(k[i+1][j+1]==49)
								{
									k[i+1][j+1]=48;
									y[d][0]=i+1;
									y[d][1]=j+1;
									d++;
								}
							}
						}
					}
				}
			}
		}
		printf("Image number %d contains %d war eagles.\n",++h,f);
	}
	return 0;
}