#include<stdio.h>
int main()
{
    int a[1000],b[1000],c[1000],d,e,f,g,h,i,j,k;
    while(scanf("%d",&d)==1)
    {
        if(d==0)
        {
            break;
        }
        for(;;)
        {
            scanf("%d",&c[0]);
            if(c[0]==0)
            {
                printf("\n");
                break;
            }
            a[0]=1;
            for(e=1;e<d;e++)
            {
                scanf("%d",&c[e]);
                a[e]=e+1;
            }
            for(e=0,f=0,g=1,h=1,j=0;e<d;e++)
            {
                if(c[e]==b[g-1]&&h==0)
                {
                    if(g>1)
                    {
                        g--;
                    }
                    else
                    {
                        h=1;
                    }
                }
                else if(f<d)
                {
                    for(i=f,j=1;i<d;i++)
                    {
                        if(a[i]==c[e])
                        {
                            j=0;
                            for(f;f<i;f++)
                            {
                                if(h==1)
                                {
                                    b[0]=a[f];
                                    h=0;
                                }
                                else
                                {
                                    b[g]=a[f];
                                    g++;
                                }
                            }
                            f=i+1;
                            break;
                        }
                    }
                    if(j==1)
                    {
                        printf("No\n");
                        break;
                    }
                }
                else
                {
                    printf("No\n");
                    j=1;
                    break;
                }
            }
            if(j!=1)
            {
                printf("Yes\n");
            }
        }
    }
    return 0;
}
