#include<stdio.h>
int main()
{
    int a[25][26],b[25][2],c,d,e,f,g,h,i,j;
    char k[20];
    while(scanf("%d",&c)==1)
    {
        for(d=0;d<c;d++)
        {
            a[d][0]=2;
            a[d][1]=d;
            b[d][0]=d;
            b[d][1]=1;
        }
        /*scanf("%c",&k[0]);
        scanf("%c",&k[0]);*/scanf("%s", k);
        for(k[0];/*k[0]!=0*/;k)
        {
            if(k[0]=='q')
            {
                /*for(d=0;d<4;d++)
                {
                    scanf("%c",&k[d]);
                }*/
                for(d=0;d<c;d++)
                {
                    printf("%d:",d);
                    for(e=1;e<a[d][0];e++)
                    {
                        printf(" %d",a[d][e]);
                    }
                    printf("\n");
                }
                break;
            }
            else if(k[0]=='m')
            {
                /*for(d=0;d<3;d++)
                {
                    scanf("%c",&k[d+1]);
                }*/
                scanf("%d",&d);
                /*scanf("%c%c%c",&k[0],&k[1],&k[2]);*/scanf("%s", k);
                if(k[1]=='n')
                {
                    /*for(e=0;e<2;e++)
                    {
                        scanf("%c",&k[e+2]);
                    }*/
                    scanf("%d",&e);
                    /*scanf("%c",&k[0]);*/
                    if(d!=e&&b[d][0]!=b[e][0])
                    {
                        g=b[d][0];
                        h=b[d][1];
                        i=b[e][0];
                        j=b[e][1];
                        for(f=h+1;f<a[g][0];f++)
                        {
                            a[a[g][f]][1]=a[g][f];
                            b[a[g][f]][0]=a[g][f];
                            b[a[g][f]][1]=1;
                            a[a[g][f]][0]++;
                        }
                        a[g][0]=h;
                        for(f=j+1;f<a[i][0];f++)
                        {
                            a[a[i][f]][1]=a[i][f];
                            b[a[i][f]][0]=a[i][f];
                            b[a[i][f]][1]=1;
                            a[a[i][f]][0]++;
                        }
                        a[i][0]=j+2;
                        a[i][j+1]=d;
                        b[d][0]=i;
                        b[d][1]=a[i][0]-1;
                    }
                }
                else
                {
                    /*for(e=0;e<2;e++)
                    {
                        scanf("%c",&k[e+2]);
                    }*/
                    scanf("%d",&e);
                    /*scanf("%c",&k[0]);*/
                    if(d!=e&&b[d][0]!=b[e][0])
                    {
                        g=b[d][0];
                        h=b[d][1];
                        i=b[e][0];
                        j=b[e][1];
                        for(f=h+1;f<a[g][0];f++)
                        {
                            a[a[g][f]][a[a[g][f]][0]]=a[g][f];
                            b[a[g][f]][0]=a[g][f];
                            b[a[g][f]][1]=a[a[g][f]][0];
                            a[a[g][f]][0]++;
                        }
                        a[g][0]=h;
                        a[i][a[i][0]]=d;
                        b[d][0]=i;
                        b[d][1]=a[i][0];
                        a[i][0]++;
                    }
                }
            }
            else
            {
                /*for(d=0;d<3;d++)
                {
                    scanf("%c",&k[d+1]);
                }*/
                scanf("%d",&d);
                /*scanf("%c%c%c",&k[0],&k[1],&k[2]);*/scanf("%s", k);
                if(k[1]=='n')
                {
                    /*for(e=0;e<2;e++)
                    {
                        scanf("%c",&k[e+2]);
                    }*/
                    scanf("%d",&e);
                    /*scanf("%c",&k[0]);*/
                    if(d!=e&&b[d][0]!=b[e][0])
                    {
                        g=b[d][0];
                        h=b[d][1];
                        i=b[e][0];
                        j=b[e][1];
                        for(f=j+1;f<a[i][0];f++)
                        {
                            a[a[i][f]][1]=a[i][f];
                            b[a[i][f]][0]=a[i][f];
                            b[a[i][f]][1]=1;
                            a[a[i][f]][0]++;
                        }
                        a[i][0]=j+1;
                        for(f=h;f<a[g][0];f++)
                        {
                            a[i][a[i][0]]=a[g][f];
                            b[a[g][f]][0]=i;
                            b[a[g][f]][1]=a[i][0];
                            a[i][0]++;
                        }
                        a[g][0]=h;
                    }
                }
                else
                {
                    /*for(e=0;e<2;e++)
                    {
                        scanf("%c",&k[e+2]);
                    }*/
                    scanf("%d",&e);
                    /*scanf("%c",&k[0]);*/
                    if(d!=e&&b[d][0]!=b[e][0])
                    {
                        g=b[d][0];
                        h=b[d][1];
                        i=b[e][0];
                        j=b[e][1];
                        for(f=h;f<a[g][0];f++)
                        {
                            a[i][a[i][0]]=a[g][f];
                            b[a[g][f]][0]=i;
                            b[a[g][f]][1]=a[i][0];
                            a[i][0]++;
                        }
                        a[g][0]=h;
                    }
                }
            }
            scanf("%s", k);
        }
    }
    return 0;
}
