#include<stdio.h>
#include<string.h>
char check[101],wei[101],comp[101][3][51],n,k,i,j,l,m,p,left,right,ans,blank;
int main()
{
	int count;
	blank=0;
	scanf("%d",&count);
	while(count--)
	{
		scanf("%d%d",&n,&k);
		memset(check,1,n);
		memset(wei,1,n);
		for(i=0;i<k;i++)
		{
			scanf("%d",&comp[i][2][50]);
			for(j=0;j<comp[i][2][50];j++)
			{
				scanf("%d",&comp[i][0][j]);
				comp[i][0][j]--;
			}
			for(j=0;j<comp[i][2][50];j++)
			{
				scanf("%d",&comp[i][1][j]);
				comp[i][1][j]--;
			}
			scanf("%s",comp[i][2]);
			if(comp[i][2][0]=='=')
			{
				for(j=0;j<comp[i][2][50];j++)
				{
					check[comp[i][0][j]]=2;
					check[comp[i][1][j]]=2;
				}
			}
			else
			{
				for(j=0;j<comp[i][2][50];j++)
				{
					if(check[comp[i][0][j]]<2)
					{
						check[comp[i][0][j]]=3;
					}
					if(check[comp[i][1][j]]<2)
					{
						check[comp[i][1][j]]=3;
					}
				}
				for(j=0;j<n;j++)
				{
					if(check[j]==3)
					{
						check[j]=1;
					}
					else
					{
						check[j]=2;
					}
				}
			}
		}
		for(i=0,ans=0;i<n;i++)
		{
			if(check[i]==1)
			{
				wei[i]++;
				for(m=0;m<k;m++)
				{
					if(comp[m][2][0]=='=')
					{
						continue;
					}
					for(p=0,left=0,right=0;p<comp[m][2][50];p++)
					{
						left+=wei[comp[m][0][p]];
						right+=wei[comp[m][1][p]];
					}
					if(left>right&&comp[m][2][0]!='>')
					{
						break;
					}
					if(left<right&&comp[m][2][0]!='<')
					{
						break;
					}
				}
				if(m==k)
				{
					if(ans)
					{
						ans=-1;
					}
					else
					{
						ans=i+1;
					}
					wei[i]--;
					continue;
				}
				wei[i]-=2;
				for(m=0;m<k;m++)
				{
					if(comp[m][2][0]=='=')
					{
						continue;
					}
					for(p=0,left=0,right=0;p<comp[m][2][50];p++)
					{
						left+=wei[comp[m][0][p]];
						right+=wei[comp[m][1][p]];
					}
					if(left>right&&comp[m][2][0]!='>')
					{
						break;
					}
					if(left<right&&comp[m][2][0]!='<')
					{
						break;
					}
				}
				if(m==k)
				{
					if(ans)
					{
						ans=-1;
					}
					else
					{
						ans=i+1;
					}
				}
				wei[i]++;
			}
		}
		if(blank)
		{
			printf("\n");
		}
		blank=1;
		if(ans<1)
		{
			printf("0\n");
		}
		else
		{
			printf("%d\n",ans);
		}
	}
	return 0;
}
