#include<stdio.h>
#include<string.h>
int main()
{
	int a,b,c,d,e,f,g,h,i,j,z[2500][2],q,r;
	char k[50][51],x,y[51],p[51], check;
	bool s[50][50];
	check = 0;
	scanf("%d",&h);
	for(h;h>0;h--)
	{
		if(check) printf("\n");
		check = 1;
		scanf("%d%d%c",&a,&b,&x);
		for(c=0;c<a;c++)
		{
			gets(k[c]);
			for(e=0,d=strlen(k[c]);e<d;e++)
			{
				if(k[c][e]<97)
				{
					k[c][e]+=32;
				}
			}
		}
		scanf("%d%c",&g,&x);
		for(g;g>0;g--)
		{
			gets(y);
			for(d=0,e=strlen(y);d<e;d++)
			{
				if(y[d]<97)
				{
					y[d]+=32;
				}
			}
			for(c=0;c<a;c++)
			{
				for(d=0;d<b;d++)
				{
					s[c][d]=0;
				}
			}
			z[0][0]=0;
			z[0][1]=0;
			for(c=0,d=1;c<d;c++)
			{
				i=z[c][0];
				j=z[c][1];
				if(k[i][j]==y[0])
				{
					p[0]=y[0];
					if(i>=e-1)
					{
						for(f=1,q=i-1;f<e;f++,q--)
						{
							p[f]=k[q][j];
						}
						p[f]='\0';
						if(strcmp(p,y)==0)
						{
							printf("%d %d\n",++i,++j);
							break;
						}
						if(j>=e-1)
						{
							for(f=1,q=i-1,r=j-1;f<e;f++,q--,r--)
							{
								p[f]=k[q][r];
							}
							p[f]='\0';
							if(strcmp(p,y)==0)
							{
								printf("%d %d\n",++i,++j);
								break;
							}
						}
						if(j+e<b+1)
						{
							for(f=1,q=i-1,r=j+1;f<e;f++,q--,r++)
							{
								p[f]=k[q][r];
							}
							p[f]='\0';
							if(strcmp(p,y)==0)
							{
								printf("%d %d\n",++i,++j);
								break;
							}
						}
					}
					if(j>=e-1)
					{
						for(f=1,r=j-1;f<e;f++,r--)
						{
							p[f]=k[i][r];
						}
						p[f]='\0';
						if(strcmp(p,y)==0)
						{
							printf("%d %d\n",++i,++j);
							break;
						}
					}
					if(j+e<b+1)
					{
						for(f=1,r=j+1;f<e;f++,r++)
						{
							p[f]=k[i][r];
						}
						p[f]='\0';
						if(strcmp(p,y)==0)
						{
							printf("%d %d\n",++i,++j);
							break;
						}
					}
					if(i+e<a+1)
					{
						for(f=1,q=i+1;f<e;f++,q++)
						{
							p[f]=k[q][j];
						}
						p[f]='\0';
						if(strcmp(p,y)==0)
						{
							printf("%d %d\n",++i,++j);
							break;
						}
						if(j>=e-1)
						{
							for(f=1,q=i+1,r=j-1;f<e;f++,q++,r--)
							{
								p[f]=k[q][r];
							}
							p[f]='\0';
							if(strcmp(p,y)==0)
							{
								printf("%d %d\n",++i,++j);
								break;
							}
						}
						if(j+e<b+1)
						{
							for(f=1,q=i+1,r=j+1;f<e;f++,q++,r++)
							{
								p[f]=k[q][r];
							}
							p[f]='\0';
							if(strcmp(p,y)==0)
							{
								printf("%d %d\n",++i,++j);
								break;
							}
						}
					}
				}
				if(i>0)
				{
					if(j>0)
					{
						if(s[i-1][j-1]==0)
						{
							z[d][0]=i-1;
							z[d][1]=j-1;
							d++;
							s[i-1][j-1]=1;
						}
					}
					if(s[i-1][j]==0)
					{
						z[d][0]=i-1;
						z[d][1]=j;
						d++;
						s[i-1][j]=1;
					}
					if(j<b-1)
					{
						if(s[i-1][j+1]==0)
						{
							z[d][0]=i-1;
							z[d][1]=j+1;
							d++;
							s[i-1][j+1]=1;
						}
					}
				}
				if(j>0)
				{
					if(s[i][j-1]==0)
					{
						z[d][0]=i;
						z[d][1]=j-1;
						d++;
						s[i][j-1]=1;
					}
				}
				if(j<b-1)
				{
					if(s[i][j+1]==0)
					{
						z[d][0]=i;
						z[d][1]=j+1;
						d++;
						s[i][j+1]=1;
					}
				}
				if(i<a-1)
				{
					if(j>0)
					{
						if(s[i+1][j-1]==0)
						{
							z[d][0]=i+1;
							z[d][1]=j-1;
							d++;
							s[i+1][j-1]=1;
						}
					}
					if(s[i+1][j]==0)
					{
						z[d][0]=i+1;
						z[d][1]=j;
						d++;
						s[i+1][j]=1;
					}
					if(j<b-1)
					{
						if(s[i+1][j+1]==0)
						{
							z[d][0]=i+1;
							z[d][1]=j+1;
							d++;
							s[i+1][j+1]=1;
						}
					}
				}
			}
		}
	}
	return 0;
}
