#include<stdio.h>
int main()
{
    char b[251],c[251];
    int a,d=0,e,f,g[501],h,i;
    while(scanf("%c",&b[0])!=EOF)
	{
		b[0]-=48;
        for(a=1;a<251;a++)
        {
            scanf("%c",&b[a]);
            if(b[a]==10)
            {
                b[a]=0;
                break;
            }
            else
            {
                b[a]-=48;
            }
        }
        for(d=0;d<251;d++)
        {
            scanf("%c",&c[d]);
            if(c[d]==10)
            {
                c[d]=0;
                break;
            }
            else
            {
                c[d]-=48;
            }
        }
		h=1;
        if(c[0]==0||b[0]==0)
        {
			if(c[0]==0)
			{
				h=0;
			    for(e=0;e<d;e++)
				{
				    if(c[e]!=0)
					{
						c[h]=c[e];
						h++;
					}
					else if(c[e]==0&&h>0)
					{
						c[h]=c[e];
						h++;
					}
				}
				if(h==0)
				{
				    printf("0\n");
				}
				else
				{
					d=h;
				}
			}
			if(b[0]==0&&h!=0)
			{
				h=0;
			    for(e=0;e<a;e++)
				{
				    if(b[e]!=0)
					{
						b[h]=b[e];
						h++;
					}
					else if(b[e]==0&&h>0)
					{
						b[h]=b[e];
						h++;
					}
				}
				if(h==0)
				{
				    printf("0\n");
				}
				else
				{
					a=h;
				}
			}
        }
        if(h!=0)
        {
            for(e=0;e<501;e++)
            {
                g[e]=0;
            }
            e=0;
            h=0;
			i=d;
            for(a;a>0;a--)
            {
                f=h;
                for(d;d>0;d--)
                {
                    e=c[d-1]*b[a-1]+e;
                    g[f]+=e%10;
                    f++;
                    e/=10;
                }
                g[f]+=e;
                e=0;
                h++;
                d=i;
            }
            for(h=0;h<501;h++)
            {
                if(g[h]>9)
                {
                    g[h+1]+=g[h]/10;
                    g[h]%=10;
                }
            }
			h=501;
            for(h;h>0;h--)
            {
                if(g[h-1]!=0)
                {
                    break;
                }
            }
            for(f=h;f>0;f--)
            {
                printf("%d",g[f-1]);
            }
            printf("\n");
        }
    }
    return 0;
}
