#include<stdio.h>
int main()
{
	int a,b,c,d,e,f[3],g[2],h[2],i[2],j[2],k[15][2];
	char l;
	double w,x,y,z;
	while(scanf("%d%c",&a,&l)==2)
	{
		if(a==0)
		{
			break;
		}
		for(b=0;b<a;b++)
		{
			scanf("%c",&l);
			scanf("%d%d",&k[b][0],&k[b][1]);
			scanf("%c",&l);
		}
		for(b=0,x=0;b<a;b++)
		{
			h[0]=k[b][0];
			h[1]=k[b][1];
			for(c=b+1;c<a;c++)
			{
				i[0]=k[c][0];
				i[1]=k[c][1];
				for(d=c+1;d<a;d++)
				{
					j[0]=k[d][0];
					j[1]=k[d][1];
					y=j[1]-h[1];
					y*=i[0]-h[0];
					y-=(i[1]-h[1])*(j[0]-h[0]);
					y/=2;
					if(y<0)
					{
						y*=-1;
					}
					for(e=0;e<a;e++)
					{
						if(e!=b&&e!=c&&e!=d)
						{
							g[0]=k[e][0];
							g[1]=k[e][1];
							w=j[1]-h[1];
							w*=g[0]-h[0];
							w-=(g[1]-h[1])*(j[0]-h[0]);
							w/=2;
							if(w<0)
							{
								w*=-1;
							}
							z=w;
							w=g[1]-h[1];
							w*=i[0]-h[0];
							w-=(i[1]-h[1])*(g[0]-h[0]);
							w/=2;
							if(w<0)
							{
								w*=-1;
							}
							z+=w;
							w=j[1]-g[1];
							w*=i[0]-g[0];
							w-=(i[1]-g[1])*(j[0]-g[0]);
							w/=2;
							if(w<0)
							{
								w*=-1;
							}
							z+=w;
							if(z==y)
							{
								break;
							}
						}
					}
					if(e==a)
					{
						if(y>x)
						{
							x=y;
							f[0]=b;
							f[1]=c;
							f[2]=d;
						}
					}
				}
			}
		}
		printf("%c%c%c\n",f[0]+65,f[1]+65,f[2]+65);
	}
	return 0;
}