#include<stdio.h>
int main()
{
    char i[10][2],j;
    int a,b,c,d,e,f,g,h[5][2],k;
    while(scanf("%c%c%c",&i[0][0],&i[0][1],&j)==3)
    {
        if(i[0][0]=='K')
        {
            i[0][0]=13;
        }
        else if(i[0][0]=='J')
        {
            i[0][0]=11;
        }
        else if(i[0][0]=='Q')
        {
            i[0][0]=12;
        }
        else if(i[0][0]=='A')
        {
            i[0][0]=14;
        }
        else if(i[0][0]=='T')
        {
            i[0][0]=10;
        }
        else
        {
            i[0][0]-=48;
        }
        for(a=1;a<10;a++)
        {
            scanf("%c%c%c",&i[a][0],&i[a][1],&j);
            if(i[a][0]=='K')
            {
                i[a][0]=13;
            }
            else if(i[a][0]=='J')
            {
                i[a][0]=11;
            }
            else if(i[a][0]=='Q')
            {
                i[a][0]=12;
            }
            else if(i[a][0]=='A')
            {
                i[a][0]=14;
            }
            else if(i[a][0]=='T')
            {
                i[a][0]=10;
            }
            else
            {
                i[a][0]-=48;
            }
        }
        for(a=0,d=0;a<4;a++)
        {
            for(b=0;b<4;b++)
            {
                if(i[b][0]>i[b+1][0])
                {
                    c=i[b][0];
                    i[b][0]=i[b+1][0];
                    i[b+1][0]=c;
                }
            }
            if(i[a][1]==i[a+1][1])
            {
                d++;
            }
        }
        if(d==4)
        {
            a=1;
        }
        for(b=0;b<5;b++)
        {
            h[b][0]=0;
            h[b][1]=0;
        }
        for(b=0,c=0;b<5;b++)
        {
            if(h[c][0]==i[b][0])
            {
                h[c][1]++;
            }
            else
            {
                if(b!=0)
                {
                    c++;
                }
                h[c][0]=i[b][0];
                h[c][1]++;
            }
        }
        if(a==1)
        {
            if(h[4][0]-h[0][0]==4)
            {
                c=9;
                d=h[4][0];
            }
            else
            {
                c=6;
                for(e=0,f=1,d=0;e<5;e++)
                {
                    d+=h[e][0]*f;
                    f*=100;
                }
            }
        }
        else
        {
            if(c==1)
            {
                if(h[0][1]==4||h[0][1]==1)
                {
                    c=8;
                    if(h[0][1]==4)
                    {
                        d=h[0][0];
                    }
                    else
                    {
                        d=h[1][0];
                    }
                }
                else
                {
                    c=7;
                    if(h[0][1]==3)
                    {
                        d=h[0][0];
                    }
                    else
                    {
                        d=h[1][0];
                    }
                }
            }
            else if(c==2)
            {
                for(d=0;d<3;d++)
                {
                    if(h[d][1]==3)
                    {
                        c=4;
                        d=h[d][0];
                        break;
                    }
                }
                if(c!=4)
                {
                    c=3;
                    for(e=0,f=100,d=0;e<3;e++)
                    {
                        if(h[e][1]==1)
                        {
                            d+=h[e][0];
                        }
                        else
                        {
                            d+=h[e][0]*f;
                            f*=f;
                        }
                    }
                }
            }
            else if(c==3)
            {
                c=2;
                for(e=0,f=1,d=0;e<4;e++)
                {
                    if(h[e][1]==2)
                    {
                        d+=h[e][0]*1000000;
                    }
                    else
                    {
                        d+=h[e][0]*f;
                        f*=100;
                    }
                }
            }
            else
            {
                if(h[4][0]-h[0][0]==4)
                {
                    c=5;
                    d=h[4][0];
                }
                else
                {
                    c=1;
                    for(e=0,f=1,d=0;e<5;e++)
                    {
                        d+=h[e][0]*f;
                        f*=100;
                    }
                }
            }
        }
        g=c;
        k=d;
        for(a=5,d=0;a<9;a++)
        {
            for(b=5;b<9;b++)
            {
                if(i[b][0]>i[b+1][0])
                {
                    c=i[b][0];
                    i[b][0]=i[b+1][0];
                    i[b+1][0]=c;
                }
            }
            if(i[a][1]==i[a+1][1])
            {
                d++;
            }
        }
        if(d==4)
        {
            a=1;
        }
        for(b=0;b<5;b++)
        {
            h[b][0]=0;
            h[b][1]=0;
        }
        for(b=5,c=0;b<10;b++)
        {
            if(h[c][0]==i[b][0])
            {
                h[c][1]++;
            }
            else
            {
                if(b!=5)
                {
                    c++;
                }
                h[c][0]=i[b][0];
                h[c][1]++;
            }
        }
        if(a==1)
        {
            if(h[4][0]-h[0][0]==4)
            {
                c=9;
                d=h[4][0];
            }
            else
            {
                c=6;
                for(e=0,f=1,d=0;e<5;e++)
                {
                    d+=h[e][0]*f;
                    f*=100;
                }
            }
        }
        else
        {
            if(c==1)
            {
                if(h[0][1]==4||h[0][1]==1)
                {
                    c=8;
                    if(h[0][1]==4)
                    {
                        d=h[0][0];
                    }
                    else
                    {
                        d=h[1][0];
                    }
                }
                else
                {
                    c=7;
                    if(h[0][1]==3)
                    {
                        d=h[0][0];
                    }
                    else
                    {
                        d=h[1][0];
                    }
                }
            }
            else if(c==2)
            {
                for(d=0;d<3;d++)
                {
                    if(h[d][1]==3)
                    {
                        c=4;
                        d=h[d][0];
                        break;
                    }
                }
                if(c!=4)
                {
                    c=3;
                    for(e=0,f=100,d=0;e<3;e++)
                    {
                        if(h[e][1]==1)
                        {
                            d+=h[e][0];
                        }
                        else
                        {
                            d+=h[e][0]*f;
                            f*=f;
                        }
                    }
                }
            }
            else if(c==3)
            {
                c=2;
                for(e=0,f=1,d=0;e<4;e++)
                {
                    if(h[e][1]==2)
                    {
                        d+=h[e][0]*1000000;
                    }
                    else
                    {
                        d+=h[e][0]*f;
                        f*=100;
                    }
                }
            }
            else
            {
                if(h[4][0]-h[0][0]==4)
                {
                    c=5;
                    d=h[4][0];
                }
                else
                {
                    c=1;
                    for(e=0,f=1,d=0;e<5;e++)
                    {
                        d+=h[e][0]*f;
                        f*=100;
                    }
                }
            }
        }
        //printf("%d %d %d %d\n",g,k,c,d);
        if(c>g)
        {
            printf("White wins.\n");
        }
        else if(c<g)
        {
            printf("Black wins.\n");
        }
        else
        {
            if(d>k)
            {
                printf("White wins.\n");
            }
            else if(d<k)
            {
                printf("Black wins.\n");
            }
            else
            {
                printf("Tie.\n");
            }
        }
    }
    return 0;
}
