#include<stdio.h>
#include<string.h>
int main()
{
	int a,b,c,d,e,f,g,h;
	char i[5][62],j[61][6], check;
	check = 0;
	strcpy(i[0],"*****..***..*...*.*****...*...*.*****.*****.***...*****.*...*");
	strcpy(i[1],"*.....*...*.*...*.*.......*...*.*...*...*...*..*..*...*..*.*.");
	strcpy(i[2],"*****.*****.*...*.***.....*****.*****...*...*...*.*...*...*..");
	strcpy(i[3],"....*.*...*..*.*..*.......*...*.*.*.....*...*..*..*...*...*..");
	strcpy(i[4],"*****.*...*...*...*****...*...*.*..**.*****.***...*****...*..");
	strcpy(j[0],"*****");
    strcpy(j[1],"*....");
    strcpy(j[2],"*****");
    strcpy(j[3],"....*");
    strcpy(j[4],"*****");
    strcpy(j[5],".....");
    strcpy(j[6],".***.");
    strcpy(j[7],"*...*");
    strcpy(j[8],"*****");
    strcpy(j[9],"*...*");
    strcpy(j[10],"*...*");
    strcpy(j[11],".....");
    strcpy(j[12],"*...*");
    strcpy(j[13],"*...*");
    strcpy(j[14],"*...*");
    strcpy(j[15],".*.*.");
    strcpy(j[16],"..*..");
    strcpy(j[17],".....");
    strcpy(j[18],"*****");
    strcpy(j[19],"*....");
    strcpy(j[20],"***..");
    strcpy(j[21],"*....");
    strcpy(j[22],"*****");
    strcpy(j[23],".....");
    strcpy(j[24],".....");
    strcpy(j[25],".....");
    strcpy(j[26],"*...*");
    strcpy(j[27],"*...*");
    strcpy(j[28],"*****");
    strcpy(j[29],"*...*");
    strcpy(j[30],"*...*");
    strcpy(j[31],".....");
    strcpy(j[32],"*****");
    strcpy(j[33],"*...*");
    strcpy(j[34],"*****");
    strcpy(j[35],"*.*..");
    strcpy(j[36],"*..**");
    strcpy(j[37],".....");
    strcpy(j[38],"*****");
    strcpy(j[39],"..*..");
    strcpy(j[40],"..*..");
    strcpy(j[41],"..*..");
    strcpy(j[42],"*****");
    strcpy(j[43],".....");
    strcpy(j[44],"***..");
    strcpy(j[45],"*..*.");
    strcpy(j[46],"*...*");
    strcpy(j[47],"*..*.");
    strcpy(j[48],"***..");
    strcpy(j[49],".....");
    strcpy(j[50],"*****");
    strcpy(j[51],"*...*");
    strcpy(j[52],"*...*");
    strcpy(j[53],"*...*");
    strcpy(j[54],"*****");
    strcpy(j[55],".....");
    strcpy(j[56],"*...*");
    strcpy(j[57],".*.*.");
    strcpy(j[58],"..*..");
    strcpy(j[59],"..*..");
    strcpy(j[60],"..*..");
	while(scanf("%d",&a)==1)
	{
		if(a==0)
		{
			break;
		}
		if(a>0)
		{
			for(b=0;b<5;b++)
			{
				for(c=0;c<a;c++)
				{
					for(d=0;d<61;d++)
					{
						for(e=0;e<a;e++)
						{
							printf("%c",i[b][d]);
						}
					}
					printf("\n");
				}
			}
		}
		else
		{
			a*=-1;
			for(b=0;b<61;b++)
			{
				for(c=0;c<a;c++)
				{
					for(d=0;d<5;d++)
					{
						for(e=0;e<a;e++)
						{
							printf("%c",j[b][d]);
						}
					}
					printf("\n");
				}
			}
		}
		printf("\n\n");
	}
	return 0;
}
