#include<stdio.h>
int a[100000][70],b,c,d,e,f,g,h,i;
int main()
{
    for(b=0;b<100000;b++)
    {
        for(c=0;c<70;c++)
        {
            a[b][c]=-1;
        }
    }
    a[0][0]=1;
    a[1][0]=1;
    printf("1\n1 1\n");
    for(b=2;b<100500;b++)
    {
        a[b][0]=1;
        for(c=b-1;c>0;c--)
        {
            for(d=0;d<70;d++)
            {
                if(a[c][d]>-1)
                {
                    if(a[c-1][d]>-1)
                    {
                        a[c][d]+=a[c-1][d];
                    }
                    else
                    {
                        for(d=0;d<69;d++)
                        {
                            if(a[c][d]>9)
                            {
                                if(a[c][d+1]<0)
                                {
                                    a[c][d+1]++;
                                }
                                a[c][d+1]++;
                                a[c][d]%=10;
                            }
                        }
                        break;
                    }
                }
                else
                {
                    if(a[c-1][d]>-1)
                    {
                        a[c][d]+=a[c-1][d]+1;
                    }
                    else
                    {
                        for(d=0;d<69;d++)
                        {
                            if(a[c][d]>9)
                            {
                                if(a[c][d+1]<0)
                                {
                                    a[c][d+1]++;
                                }
                                a[c][d+1]++;
                                a[c][d]%=10;
                            }
                        }
                        break;
                    }
                }
            }
        }
        for(c=0;c<=b;c++)
        {
            if(c!=0)
            {
                printf(" ");
            }
            for(d=70;d>0;d--)
            {
                if(a[c][d-1]>-1)
                {
                    printf("%d",a[c][d-1]);
                }
            }
        }
        printf("\n");
        if(a[b/2+1][60]>0)
        {
            break;
        }
    }
    return 0;
}
