#include<stdio.h>
int a[100000][3],b,c,d,e,f,g,h,i,j,m[32][32][32];
int main()
{
    char k,l[32][32][32];
    while(scanf("%d %d %d%c",&b,&c,&d,&k)==4)
    {
    	if(b==0&&c==0&&d==0)
    	{
    	    break;
    	}
    	for(e=0;e<b;e++)
    	{
    	    for(f=0;f<c;f++)
    	    {
    	    	for(g=0;g<d;g++)
        		{
        		    scanf("%c",&l[e][f][g]);
        		    m[e][f][g]=100000;
        		    if(l[e][f][g]=='S')
        		    {
        	    		h=e;
            			i=f;
            			j=g;
            			m[e][f][g]=0;
        		    }
        		}
        		scanf("%c",&k);
    	    }
    	    if(e!=b-1)
    	    {
        	    scanf("%c",&k);
    	    }
    	}
    	a[0][0]=h;
    	a[0][1]=i;
    	a[0][2]=j;
    	for(e=0,f=1,k=0,h=1;e<100000;e++)
    	{
    	    //printf("%d\n",e);
    	    if(e>h)
    	    {
    	        break;
    	    }
    	    if(a[e][0]>0)
    	    {
    	        f=m[a[e][0]][a[e][1]][a[e][2]]+1;
    		    a[e][0]--;
        		if(l[a[e][0]][a[e][1]][a[e][2]]=='E')
        		{
        		    k=1;
        		    a[e][0]=0;
        		    a[e][1]=0;
        		    a[e][2]=0;
        		    break;
        		}
        		if(l[a[e][0]][a[e][1]][a[e][2]]=='.')
        		{
        		    if(m[a[e][0]][a[e][1]][a[e][2]]>f)
        		    {
            			m[a[e][0]][a[e][1]][a[e][2]]=f;
            			a[h][0]=a[e][0];
            			a[h][1]=a[e][1];
            			a[h][2]=a[e][2];
            			h++;
            			/*for(j=0;j<3;j++)
            			{
            			    printf("%d ",a[e][j]);
            			}
            			printf("\n");*/
        		    }
        		}
        		a[e][0]++;
    	    }
    	    if(a[e][1]>0)
    	    {
    	        f=m[a[e][0]][a[e][1]][a[e][2]]+1;
    	    	a[e][1]--;
        		if(l[a[e][0]][a[e][1]][a[e][2]]=='E')
        		{
        		    k=1;
        		    a[e][0]=0;
        		    a[e][1]=0;
        		    a[e][2]=0;
        		    break;
        		}
        		if(l[a[e][0]][a[e][1]][a[e][2]]=='.')
        		{
        		    if(m[a[e][0]][a[e][1]][a[e][2]]>f)
        		    {
            			m[a[e][0]][a[e][1]][a[e][2]]=f;
            			a[h][0]=a[e][0];
            			a[h][1]=a[e][1];
            			a[h][2]=a[e][2];
            			h++;
            			/*for(j=0;j<3;j++)
            			{
            			    printf("%d ",a[e][j]);
            			}
            			printf("\n");*/
        		    }
        		}
        		a[e][1]++;
    	    }
    	    if(a[e][2]>0)
    	    {
    	        f=m[a[e][0]][a[e][1]][a[e][2]]+1;
    	    	a[e][2]--;
        		if(l[a[e][0]][a[e][1]][a[e][2]]=='E')
        		{
        		    k=1;
        		    a[e][0]=0;
        		    a[e][1]=0;
        		    a[e][2]=0;
        		    break;
        		}
        		if(l[a[e][0]][a[e][1]][a[e][2]]=='.')
        		{
        		    if(m[a[e][0]][a[e][1]][a[e][2]]>f)
        		    {
            			m[a[e][0]][a[e][1]][a[e][2]]=f;
                        a[h][0]=a[e][0];
            			a[h][1]=a[e][1];
            			a[h][2]=a[e][2];
            			h++;
            			/*for(j=0;j<3;j++)
            			{
            			    printf("%d ",a[e][j]);
            			}
            			printf("\n");*/
        		    }
        		}
        		a[e][2]++;
    	    }
    	    if(a[e][0]<b-1)
    	    {
    	        f=m[a[e][0]][a[e][1]][a[e][2]]+1;
    	    	a[e][0]++;
        		if(l[a[e][0]][a[e][1]][a[e][2]]=='E')
        		{
        		    k=1;
        		    a[e][0]=0;
        		    a[e][1]=0;
        		    a[e][2]=0;
        		    break;
        		}
        		if(l[a[e][0]][a[e][1]][a[e][2]]=='.')
        		{
        		    if(m[a[e][0]][a[e][1]][a[e][2]]>f)
        		    {
            			m[a[e][0]][a[e][1]][a[e][2]]=f;
            			a[h][0]=a[e][0];
            			a[h][1]=a[e][1];
            			a[h][2]=a[e][2];
            			h++;
            			/*for(j=0;j<3;j++)
            			{
            			    printf("%d ",a[e][j]);
            			}
            			printf("\n");*/
        		    }
        		}
        		a[e][0]--;
    	    }
    	    if(a[e][1]<c-1)
    	    {
    	        f=m[a[e][0]][a[e][1]][a[e][2]]+1;
    	    	a[e][1]++;
        		if(l[a[e][0]][a[e][1]][a[e][2]]=='E')
        		{
        		    k=1;
        		    a[e][0]=0;
        		    a[e][1]=0;
        		    a[e][2]=0;
        		    break;
        		}
        		if(l[a[e][0]][a[e][1]][a[e][2]]=='.')
        		{
        		    if(m[a[e][0]][a[e][1]][a[e][2]]>f)
        		    {
            			m[a[e][0]][a[e][1]][a[e][2]]=f;
            			a[h][0]=a[e][0];
            			a[h][1]=a[e][1];
            			a[h][2]=a[e][2];
            			h++;
            			/*for(j=0;j<3;j++)
            			{
            			    printf("%d ",a[e][j]);
            			}
            			printf("\n");*/
        		    }
        		}
        		a[e][1]--;
    	    }
    	    if(a[e][2]<d-1)
    	    {
    	        f=m[a[e][0]][a[e][1]][a[e][2]]+1;
    	    	a[e][2]++;
        		if(l[a[e][0]][a[e][1]][a[e][2]]=='E')
        		{
        		    k=1;
        		    a[e][0]=0;
        		    a[e][1]=0;
        		    a[e][2]=0;
        		    break;
        		}
        		if(l[a[e][0]][a[e][1]][a[e][2]]=='.')
        		{
        		    if(m[a[e][0]][a[e][1]][a[e][2]]>f)
        		    {
            			m[a[e][0]][a[e][1]][a[e][2]]=f;
            			a[h][0]=a[e][0];
            			a[h][1]=a[e][1];
            			a[h][2]=a[e][2];
            			h++;
            			/*for(j=0;j<3;j++)
            			{
            			    printf("%d ",a[e][j]);
            			}
            			printf("\n");*/
        		    }
        		}
        		a[e][2]--;
    	    }
    	    a[e][0]=0;
    	    a[e][1]=0;
    	    a[e][2]=0;
    	}
    	if(k==1)
    	{
    	    printf("Escaped in %d minute(s).\n",f);
    	}
    	else
    	{
    	    printf("Trapped!\n");
    	}
    }
    return 0;
}
