#include<stdio.h>
int main()
{
    int a,b,c,d,e,f,g,h;
    while(scanf("%d %d %d",&a,&b,&c)==3)
    {
        if(a==0&&b==0&&c==0)
        {
            break;
        }
        if(a>12)
        {
            printf("%d/%d/%d is an invalid date.\n",a,b,c);
        }
        else
        {
            if(a==4||a==6||a==9||a==11)
            {
                if(b<31)
                {
                    d=1;
                }
                else
                {
                    d=0;
                }
                if(c==1752&&a==9)
                {
                    if(b>2&&b<14)
                    {
                        d=0;
                    }
                }
            }
            else if(a==2)
            {
                if(c>1752)
                {
                    if(c%4==0)
                    {
                        if(c%100==0&&c%400!=0)
                        {
                            if(b<29)
                            {
                                d=1;
                            }
                            else
                            {
                                d=0;
                            }
                        }
                        else
                        {
                            if(b<30)
                            {
                                d=1;
                            }
                            else
                            {
                                d=0;
                            }
                        }
                    }
                    else
                    {
                        if(b<29)
                        {
                            d=1;
                        }
                        else
                        {
                            d=0;
                        }
                    }
                }
                else
                {
                    if(c%4==0)
                    {
                        if(b<30)
                        {
                            d=1;
                        }
                        else
                        {
                            d=0;
                        }
                    }
                    else
                    {
                        if(b<29)
                        {
                            d=1;
                        }
                        else
                        {
                            d=0;
                        }
                    }
                }
            }
            else
            {
                if(b<32)
                {
                    d=1;
                }
                else
                {
                    d=0;
                }
            }
            if(d==1)
            {
                d=c-1;
                d+=(c-1)/4;
                if(c>1752)
                {
                    d+=(c-1)/400;
                    d-=(c-1)/100;
                    d+=2;
                    if(c%4==0)
                    {
                        if(c%100!=0||c%400==0)
                        {
                            if(a>2)
                            {
                                d++;
                            }
                        }
                    }
                }
                else if(c==1752)
                {
                    if(a>9||a==9&&b>2)
                    {
                        d-=11;
                    }
                    if(a>2)
                    {
                        d++;
                    }
                }
                else
                {
                    if(c%4==0)
                    {
                        if(a>2)
                        {
                            d++;
                        }
                    }
                }
                d+=(a-1)*30+b;
                if(a>8)
                {
                    d+=a%2;
                }
                if(a>2)
                {
                    d+=a/2-2;
                }
                else
                {
                    d+=a/2;
                }
                d--;
                d%=7;
                if(a==1)
                {
                    printf("January ");
                }
                if(a==2)
                {
                    printf("February ");
                }
                if(a==3)
                {
                    printf("March ");
                }
                if(a==4)
                {
                    printf("April ");
                }
                if(a==5)
                {
                    printf("May ");
                }
                if(a==6)
                {
                    printf("June ");
                }
                if(a==7)
                {
                    printf("July ");
                }
                if(a==8)
                {
                    printf("August ");
                }
                if(a==9)
                {
                    printf("September ");
                }
                if(a==10)
                {
                    printf("October ");
                }
                if(a==11)
                {
                    printf("November ");
                }
                if(a==12)
                {
                    printf("December ");
                }
                printf("%d, %d is a ",b,c);
                if(d==0)
                {
                    printf("Saturday\n");
                }
                if(d==1)
                {
                    printf("Sunday\n");
                }
                if(d==2)
                {
                    printf("Monday\n");
                }
                if(d==3)
                {
                    printf("Tuesday\n");
                }
                if(d==4)
                {
                    printf("Wednesday\n");
                }
                if(d==5)
                {
                    printf("Thursday\n");
                }
                if(d==6)
                {
                    printf("Friday\n");
                }
            }
            else
            {
                printf("%d/%d/%d is an invalid date.\n",a,b,c);
            }
        }
    }
    return 0;
}
