#include<stdio.h>
#include<string.h>
int main()
{
	int count;
	char res[3][3][14],i,j,k,l,m,n,lef,rig,wei[12],check[12];
	scanf("%d",&count);
	while(count--)
	{
		memset(check,1,12);
		for(i=0;i<3;i++)
		{
			scanf("%s%s%s",res[i][0],res[i][1],res[i][2]);
			res[i][2][13]=strlen(res[i][0]);
			k=0;
			if(res[i][2][0]=='e')
			{
				k=1;
			}
			for(j=0;j<res[i][2][13];j++)
			{
				res[i][0][j]-=65;
				if(check[res[i][0][j]])
				{
					check[res[i][0][j]]-=k;
				}
				res[i][1][j]-=65;
				if(check[res[i][1][j]])
				{
					check[res[i][1][j]]-=k;
				}
			}
		}
		memset(wei,1,12);
		for(i=0;i<3;i++)
		{
			if(res[i][2][0]=='e')
			{
				continue;
			}
			else if(res[i][2][0]=='u')
			{
				k=1;
			}
			else
			{
				k=-1;
			}
			for(j=0;j<res[i][2][13];j++)
			{
				if(check[res[i][0][j]])
				{
					wei[res[i][0][j]]+=k;
					for(l=0;l<3;l++)
					{
						if(l==i||res[l][2][0]=='e')
						{
							continue;
						}
						for(m=0,lef=0,rig=0;m<res[l][2][13];m++)
						{
							lef+=wei[res[l][0][m]];
							rig+=wei[res[l][1][m]];
						}
						if(lef==rig&&res[l][2][0]!='e')
						{
							break;
						}
						if(lef>rig&&res[l][2][0]!='u')
						{
							break;
						}
						if(lef<rig&&res[l][2][0]!='d')
						{
							break;
						}
					}
					if(l==3)
					{
						if(k==1)
						{
							strcpy(check,"heavy");
							k=res[i][0][j];
						}
						else
						{
							strcpy(check,"light");
							k=res[i][0][j];
						}
						break;
					}
					wei[res[i][0][j]]-=k;
				}
				check[res[i][0][j]]=0;
				if(check[res[i][1][j]])
				{
					wei[res[i][1][j]]-=k;
					for(l=0;l<3;l++)
					{
						if(l==i||res[l][2][0]=='e')
						{
							continue;
						}
						for(m=0,lef=0,rig=0;m<res[l][2][13];m++)
						{
							lef+=wei[res[l][0][m]];
							rig+=wei[res[l][1][m]];
						}
						if(lef==rig&&res[l][2][0]!='e')
						{
							break;
						}
						if(lef>rig&&res[l][2][0]!='u')
						{
							break;
						}
						if(lef<rig&&res[l][2][0]!='d')
						{
							break;
						}
					}
					if(l==3)
					{
						if(k==1)
						{
							strcpy(check,"light");
							k=res[i][1][j];
						}
						else
						{
							strcpy(check,"heavy");
							k=res[i][1][j];
						}
						break;
					}
					wei[res[i][1][j]]+=k;
				}
				check[res[i][1][j]]=0;
			}
			if(j<res[i][2][13])
			{
				break;
			}
		}
		printf("%c is the counterfeit coin and it is %s.\n",k+65,check);
	}
	return 0;
}